<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40757" started-at="2019-11-10T00:07:08Z" finished-at="2019-11-10T00:07:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40757" started-at="2019-11-10T00:07:08Z" finished-at="2019-11-10T00:07:49Z">
      <class name="mct.testrunner.myTestngTest">
        <test-method status="PASS" signature="rampUP()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampUP" is-config="true" duration-ms="4805" started-at="2019-11-10T00:07:08Z" finished-at="2019-11-10T00:07:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampUP -->
        <test-method status="FAIL" signature="logOut()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="logOut" duration-ms="5448" started-at="2019-11-10T00:07:13Z" finished-at="2019-11-10T00:07:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed Login Doesn't Happend expected [XNULLX] but found [NULL]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed Login Doesn't Happend expected [XNULLX] but found [NULL]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at mct.testrunner.myTestngTest.logOut(myTestngTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method status="PASS" signature="rampDown()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampDown" is-config="true" duration-ms="1" started-at="2019-11-10T00:07:19Z" finished-at="2019-11-10T00:07:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampDown -->
        <test-method status="PASS" signature="rampUP()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampUP" is-config="true" duration-ms="4245" started-at="2019-11-10T00:07:19Z" finished-at="2019-11-10T00:07:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampUP -->
        <test-method status="PASS" signature="login()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="login" duration-ms="2804" started-at="2019-11-10T00:07:23Z" finished-at="2019-11-10T00:07:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="rampDown()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampDown" is-config="true" duration-ms="0" started-at="2019-11-10T00:07:26Z" finished-at="2019-11-10T00:07:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampDown -->
        <test-method status="PASS" signature="rampUP()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampUP" is-config="true" duration-ms="4698" started-at="2019-11-10T00:07:26Z" finished-at="2019-11-10T00:07:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampUP -->
        <test-method status="PASS" signature="myAccount()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="myAccount" duration-ms="5897" started-at="2019-11-10T00:07:30Z" finished-at="2019-11-10T00:07:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myAccount -->
        <test-method status="PASS" signature="rampDown()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampDown" is-config="true" duration-ms="0" started-at="2019-11-10T00:07:36Z" finished-at="2019-11-10T00:07:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampDown -->
        <test-method status="PASS" signature="rampUP()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampUP" is-config="true" duration-ms="4799" started-at="2019-11-10T00:07:36Z" finished-at="2019-11-10T00:07:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampUP -->
        <test-method status="FAIL" signature="signUP()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="signUP" duration-ms="8018" started-at="2019-11-10T00:07:41Z" finished-at="2019-11-10T00:07:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed To FInd Proper Profile Name After Registration expected [mr abc346] but found [MR ABC346]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed To FInd Proper Profile Name After Registration expected [mr abc346] but found [MR ABC346]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at mct.testrunner.myTestngTest.signUP(myTestngTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUP -->
        <test-method status="PASS" signature="rampDown()[pri:0, instance:mct.testrunner.myTestngTest@58651fd0]" name="rampDown" is-config="true" duration-ms="0" started-at="2019-11-10T00:07:49Z" finished-at="2019-11-10T00:07:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampDown -->
      </class> <!-- mct.testrunner.myTestngTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
